### ISSUE TITLE
Missing call to addEmailOrUserIdToJson in IterableApi.trackInAppClick

### ISSUE THREAD

**Issue by guillaume-gouchon** [Iterable/iterable-android-sdk#13]
Hi,

in IterableApi class, we cannot use trackInAppClick method if we initialised the api with a userId, and not with an email address. 
(https://github.com/Iterable/iterable-android-sdk/blob/master/iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java#L601)

Indeed, in the method's body, the email is compulsory :

       JSONObject requestJSON = new JSONObject();
        try {
            requestJSON.put("email", this._email);// here is the issue
            requestJSON.put("campaignId", campaignId);
            requestJSON.put("templateId", templateId);
            requestJSON.put("messageId", messageId);
            requestJSON.put("buttonIndex", buttonIndex);
        } catch (JSONException var7) {
            var7.printStackTrace();
        }

        this.sendPostRequest("events/trackInAppClick", requestJSON);

Instead, I propose to call the private method addEmailOrUserIdToJson :

       JSONObject requestJSON = new JSONObject();
        try {
            addEmailOrUserIdToJson(requestJSON);// here is the fix
            requestJSON.put("campaignId", campaignId);
            requestJSON.put("templateId", templateId);
            requestJSON.put("messageId", messageId);
            requestJSON.put("buttonIndex", buttonIndex);
        } catch (JSONException var7) {
            var7.printStackTrace();
        }

        this.sendPostRequest("events/trackInAppClick", requestJSON);

In our use-case , we keep receiving error message: "Either email or userId must be specified" because of this.

Thanks by advance !

**Comment by davidtruong** [comment]
Thanks,

I'll get a Jira ticket made for this and get it triaged. It should hopefully be in the next release of our SDK.

-DT

**Comment by davidtruong** [comment]
Fixed in https://github.com/Iterable/iterable-android-sdk/pull/15

**Comment by davidtruong** [comment]
Released: https://github.com/Iterable/iterable-android-sdk/releases/tag/2.1.6
