### ISSUE TITLE
Static method for detecting Ghost Pushes

### ISSUE THREAD

**Issue by grahamsmith** [Iterable/iterable-android-sdk#143]
On receipt of a push apps can perform other steps whilst also handling Iterable push. Since there is only a single static method entry point to handle a push notification and the ghost detection is handled internally, there is no way for the host app to make any further decisions about to proceed.

A static method with the following code would be suffice to solve this issue:

```
@JvmStatic
fun isGhostPush(remoteMessage: RemoteMessage?) {

 val messageData = remoteMessage?.getData()

        if (messageData == null || messageData.isEmpty()) {
            return false
        }
        
        if (messageData.containsKey(IterableConstants.ITERABLE_DATA_KEY)) {
            
            val iterableData = messageData[IterableConstants.ITERABLE_DATA_KEY]

            val iterableJson = JSONObject(iterableData) //needs to handle JSON related exceptions
            return iterableJson.optBoolean(IterableConstants.IS_GHOST_PUSH)
        }
}
```

**Comment by vbabenkoru** [comment]
@grahamsmith Are you processing Iterable messages in the app somehow? Would just having `isIterablePush` be enough?

**Comment by grahamsmith** [comment]
It has taken **4 months** to get a reply to this 😐

To answer your question - No.

We perform actions **before** the user sees the push so when they act upon it the App is in a great state for them. We do not want to perform these actions when receiving a ghost push.

**Comment by vbabenkoru** [comment]
@grahamsmith I'm sorry it took so long. :(
Got it, thank you. We'll release an update with this soon.

**Comment by grahamsmith** [comment]
@vbabenkoru that's great news. Thanks for sorting it.

**Comment by vbabenkoru** [comment]
@grahamsmith A new release with this method is now available: https://github.com/Iterable/iterable-android-sdk/releases/tag/3.1.6

**Comment by grahamsmith** [comment]
@vbabenkoru that's great news thanks!
