### ISSUE TITLE
Crash with Picasso when showing a fullscreen in-app notification without image url

### ISSUE THREAD

**Issue by guillaume-gouchon** [Iterable/iterable-android-sdk#18]
Hi,

When showing a fullscreen in-app notification without image, the app crashes because of Picasso loading an empty path image: 
 java.lang.IllegalArgumentException: Path must not be empty.
com.squareup.picasso.Picasso.load(Picasso.java:297)
com.iterable.iterableapi.IterableInAppManager.showFullScreenDialog(IterableInAppManager.java:163)
com.iterable.iterableapi.IterableInAppManager.showNotification(IterableInAppManager.java:44)
...

Please can you check for the presence of an image here, before calling Picasso.load :
https://github.com/Iterable/iterable-android-sdk/blob/master/iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java#L163

Something like that:

`Class picassoClass = Class.forName(IterableConstants.PICASSO_CLASS);
if (picassoClass != null && dialogParameters.optString(IterableConstants.ITERABLE_IN_APP_MAIN_IMAGE) != null) {
 Picasso.with(context.getApplicationContext()).load(dialogParameters.optString(IterableConstants.ITERABLE_IN_APP_MAIN_IMAGE)).
                        resize(dialogWidth, dialogHeight/2).
                        centerInside().
                        into(imageView);
}`

**Comment by davidtruong** [comment]
dialogParameters.optString actually falls back to an empty string which is what I had originally accounted for. However Picasso seems to fail to load the empty string. 

I changed the check to !(dialogParameters.optString(IterableConstants.ITERABLE_IN_APP_MAIN_IMAGE)).isEmpty
I have the fix in a PR now. I should have the fix out soon.

**Comment by davidtruong** [comment]
Fixed in release version 2.1.8.
