### ISSUE TITLE
rich push notification not work when app in background or kill

### ISSUE THREAD

**Issue by hoangnam9194** [Iterable/iterable-android-sdk#193]
i sent a push from web app.iterable.com, included Rich media URL (image) option.
but the notification's image didn't show when app on background/kill, only show on foreground.
look like our platform use Notification Message type instead of Data Message type?

**Comment by vbabenkoru** [comment]
Thank you for the report.
We do support rendering when the app is in background or killed.
This issue looks app-specific and requires looking into the specific settings in your Iterable project to troubleshoot, and Github Issues can only be used for code-level support. Please open a ticket with our Customer Support mentioning this Github ticket.
Thank you.

**Comment by hoangnam9194** [comment]
hi @vbabenkoru ,
can you give me an example project which work with rich notification regardless app in background or killed?
I want to refer to their configuration.
thank you.

**Comment by vbabenkoru** [comment]
Make sure OS Notifications is set to OFF for the Firebase integration in Iterable settings.

**Comment by vbabenkoru** [comment]
Please let us know if that worked, and if you need further help, please reach out to your CSM or to Support.
