### ISSUE TITLE
Clicking on push notification not doing deep linking.

### ISSUE THREAD

**Issue by iamjosephmj** [Iterable/iterable-android-sdk#221]
- Open the app.
- get a push notification.
- close all the activities.
- Click on the push notification received(application is no longer running now).

result:
there will be no action taken(deeplink handler is not called).

SDK version(3.2.0)
OS: Android 10(one-plus 7 pro)

**Comment by vbabenkoru** [comment]
Thank you for the report. We'll investigate and get back to you.

**Comment by Ayyanchira** [comment]
Hi @iamjosephmj, I followed your steps but couldn't reproduce the issue. The deeplink handler was invoked properly. A simple way to test if the deeplink handler is getting called would be to print/log something inside the method `handleIterableURL`

Also, does it occur only to specific OS and device you mentioned? Does it work on other OS/device/emulator properly?

**Comment by Ayyanchira** [comment]
Another check mark before going into details:
Is the SDK Initialized during Application's oncreate✅ ? or is it Activity's oncreate ❌?

It is necessary for Iterable SDK to be initialized when the application is starting, to make sure everything is set up.

**Comment by iamjosephmj** [comment]
Hey @Ayyanchira, This is the configuration that I have done:
- Initialized Iterable SDK in the Application class
- Implemented the deep link handler for the same(handleIterableURL).
* I have actually followed all the steps that are given in "https://github.com/Iterable/iterable-android-sdk" 
- I am able to get the push notification and make the deep link work in this way.

deep-link is working in these 2 scenarios with my app:
- When the app closed and a push is received.
- When the app is opened and a push is received.

**BUT**
suppose we get a push notification when the application is opened, and after that, I closed the application.
Then when I click on the push notification there is no action taken in the deep link handler.

I have tried logging method, Still, nothing is getting logged in this scenario.

Please let me know If I need to provide any more details.
Thanks.

**Comment by iamjosephmj** [comment]
This happens only with OnePlus7pro (Android 10).

**Comment by Ayyanchira** [comment]
This definitely needs further investigation. Thanks for sharing those details @iamjosephmj . We will get back to you.

**Comment by Ayyanchira** [comment]
Hi @iamjosephmj, need another piece of information. when you say no action is taken in deep handler, does the app launch? Or is it just the deep link handler function not getting invoked?

**Comment by Ayyanchira** [comment]
Receiving a push notification and then killing the app should have no problem. Tapping on the notification should ideally launch the application's background processes (eventually leading to deeplink callback and app launch).

This seems to be OnePlus's way of handling notification which is preventing app launch. I would suggest you try disabling battery optimization options like **Deep Optimization** and **Sleep standby optimization** and try it again.
You will find additional info here: https://dontkillmyapp.com/oneplus

**Comment by iamjosephmj** [comment]
@Ayyanchira "https://dontkillmyapp.com/oneplus" resolved the issue I had. 
Thankyou.
