### ISSUE TITLE
Don't distribute strings.xml with app_name

### ISSUE THREAD

**Issue by Naitbit** [Iterable/iterable-android-sdk#242]
Distributing strings.xml with app_name in for example `com.iterable:iterableapi` may surprise users by accidentally overriding name of their app.
Sure apps can workaround it, but it seems that it would be better to fix it at library level.

Possible fixes include:
- Hardcode value in AndroidManifest.xml (as it is used only there, and it is not translated)
   - this has advantage of making library slightly smaller and apps that use SDK don't have to merge strings.xml during the build process
- Rename `app_name` to something more specific like `iterableapi_app_name` which is unlikely to cause conflicts for users

PR: https://github.com/Iterable/iterable-android-sdk/issues/242

**Comment by vbabenkoru** [comment]
Fixed via #243
