### ISSUE TITLE
Is there a way to manually track push notification opens? 

### ISSUE THREAD

**Issue by byamba3** [Iterable/iterable-android-sdk#246]
Currently, the Iterable SDK automatically tracks push open in `IterablePushActionReceiver.kt`. But what if we want to manually track iterable push opens to our own tracking system? This is what I'm doing now. 

```
        val config = IterableConfig.Builder()
            .setUrlHandler { uri, actionContext ->
                if (actionContext.source == IterableActionSource.PUSH){
                   // do manual tracking
               }
                application.startActivity(
                    Intent(Intent.ACTION_VIEW, uri).apply {
                        addFlags(
                            Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_NEW_TASK
                        )
                    }
                )
                true
            }
            .build()
```

Is above the right and the only way? It seems like we can't track the campaign name and template name that way, unfortunately. It would have been great if there was an option to add our own manual tracking.

**Comment by vbabenkoru** [comment]
@byamba3 You can get campaignId and templateId by calling `getAttributionInfo`.
