### ISSUE TITLE
Expose expiresAt in IterableInAppMessage to prioritize by expiration date

### ISSUE THREAD

**Issue by andreygorilla** [Iterable/iterable-android-sdk#269]
Hi I need to prioritize in-app messages by expiration date but it is currently private into `IterableInAppMessage`

Could you please add a getter method or any way to read `private final @NonNull Date expiresAt;` outside Iterable SDK?

I appreciate if this change can be done.

Thanks

Andrey

**Comment by vbabenkoru** [comment]
Fixed via #271. This will be in the next release of the SDK.

**Comment by andreygorilla** [comment]
Thank you :)
