### ISSUE TITLE
Setup Guide Not Accessible

### ISSUE THREAD

**Issue by grndvl1** [Iterable/iterable-android-sdk#27]
Why do you have a link to a guide that I have to login for and then it says I don't have permissions to see that page.  http://support.iterable.com/hc/en-us/articles/204780589-Push-Notification-Setup-iOS-and-Android-

**Comment by davidtruong** [comment]
Thanks for pointing this out! :)

Sorry we migrated over to separate docs for Android vs iOS. The old article still exists and points to the new docs, however it looks like we recently removed permissions to it.

Here's a link to the correct android article: https://support.iterable.com/hc/en-us/articles/115000331943-Setting-up-Android-Push-Notifications

I'll up the readme to reflect that. 👍
