### ISSUE TITLE
The in-app message fails to auto display at times

### ISSUE THREAD

**Issue by byamba3** [Iterable/iterable-android-sdk#289]
I've noticed that sometimes when the app opens, it tries to display the in-app message before the current activity reaches onResume, and therefore the `showMessage()` of `IterableInAppDisplayer` seems to return false (meaning the message never gets displayed) since the current activity is null until onResume. I think this could be fixed by ensuring the message processing happens only after the current activity has reached onResume. It's a tricky race condition that may be harder to replicate in some apps.

Few other suggestions:

- Since manually calling `inAppManager.showMessage(message)` needs to happen after `onResume`, it should probably be noted in the documentation. I was calling `showMessage` multiple times and was very confused when it wasn't doing anything.
- How can one manually add a listener that gets called whenever a new message is received? The inAppManager has an `addListener` method but it gets called for general dataset changes, and not exclusive for new messages. I'm trying to emulate the behavior of the auto display when auto-display is disabled (via `InAppResponse.SKIP`).

**Comment by vbabenkoru** [comment]
> I've noticed that sometimes when the app opens, it tries to display the in-app message before the current activity reaches onResume, and therefore the `showMessage()` of `IterableInAppDisplayer` seems to return false (meaning the message never gets displayed) since the current activity is null until onResume. I think this could be fixed by ensuring the message processing happens only after the current activity has reached onResume. It's a tricky race condition that may be harder to replicate in some apps.
Hmm, interesting. We do have the following check before processing:
```
if (!activityMonitor.isInForeground() || isShowingInApp() || !canShowInAppAfterPrevious() || isAutoDisplayPaused()) {
    return;
}
```
`activityMonitor.isInForeground()` is only true if there is a resumed activity on the screen.

> * Since manually calling `inAppManager.showMessage(message)` needs to happen after `onResume`, it should probably be noted in the documentation. I was calling `showMessage` multiple times and was very confused when it wasn't doing anything.
Good point! We'll update the documentation, thanks.

> * How can one manually add a listener that gets called whenever a new message is received? The inAppManager has an `addListener` method but it gets called for general dataset changes, and not exclusive for new messages. I'm trying to emulate the behavior of the auto display when auto-display is disabled (via `InAppResponse.SKIP`).
`inAppHandler` itself should be the place where you get notified about new messages.
You can also use the listener and check if there are any unread messages (`message.isRead() == false`). It depends on the use case.

**Comment by byamba3** [comment]
Thanks for the quick response, @vbabenkor. I did some more digging, and I think found the culprit for why in-app messages weren't showing. Our app has a special SplashActivity that's the _true_ first activity when the app gets launched. We use this activity to choose which MainActivities we want to launch (for example, one of the MainActivity is for instant apps). So it seems that Iterable tries to display the in-app message in SplashActivity, but that activity closes quickly and redirects to MainActivity. 

I'm doing a hacky workaround by calling `setAutoDisplayPaused(true)` on Application start, and MainActivity onPause. Then calling `setAutoDisplayPaused(false)` on MainActivity onResume. That ensures we only process the message in the MainActivity. I think ideally, it would be great if there was a way to configure our true MainActivity. Or maybe, don't set the message as read until it's truly fully shown or closed by the user? Not sure what's best.

**Comment by byamba3** [comment]
Solved via setting auto display on/off manually.
