### ISSUE TITLE
Functionality to temporarily disable Popups?

### ISSUE THREAD

**Issue by Parithi** [Iterable/iterable-android-sdk#324]
Hi Team,

We've been using Iterable on our apps and its working pretty great so far! However, we are experiencing some issues on both iOS and Android apps. 

We have HTML popups scheduled for our new users that would show up on the app after their first login that is triggered based on events made by the user. However, in order to better control the popups, is there a way to temporarily `pause` the functionality of Iterable SDK that shows the popups. And `resume` when needed?

It would be helpful for us to define when the Iterable Popups are allowed to shown or be hidden and displayed later. Right now, it seems to get displayed on top of our app at any moment.

**Comment by Ayyanchira** [comment]
Yes absolutely! We recently released a new feature - inAppDisplayPause`

[iOS support documentation ](https://support.iterable.com/hc/en-us/articles/360035536791-In-App-Messages-on-iOS-#pausing-the-display-of-in-app-messages)
[Android support documentation](https://support.iterable.com/hc/en-us/articles/360035537231-In-App-Messages-on-Android-#pausing-the-display-of-in-app-messages-sdk-v3-2-6-and-above)

**Comment by Parithi** [comment]
Thank you! :)
