### ISSUE TITLE
Mobile inbox opens as a blank page

### ISSUE THREAD

**Issue by korva** [Iterable/iterable-android-sdk#328]
I've got the Iterable SDK working nicely otherwise (receiving push notifications and inapp messages), but setting up and opening mobile inbox according to these instructions
https://support.iterable.com/hc/en-us/articles/360038744152

...opens a new activity which shows just a blank white page.

Using
```
implementation 'com.iterable:iterableapi:3.2.10'
implementation 'com.iterable:iterableapi-ui:3.2.10'
```

Running on Android emulator API 30.

Code to open activity:
`startActivity(Intent(context, IterableInboxActivity::class.java))`

No hints found from logcat.

**Comment by Ayyanchira** [comment]
Hi @korva, 
Did the inapp had `inbox` flag turned on?

IterableInboxActivity will only show in-apps which have the checkbox ticked. Otherwise it will be a blank screen.

<img width="191" alt="image" src="https://user-images.githubusercontent.com/22951141/111366112-59618100-8650-11eb-88af-0cc6aa06926f.png">

**Comment by korva** [comment]
Yeah, that was it, thanks! Would be a better user experience if the empty state had something in it, maybe some "No messages" text?

Also, when I opened the inbox the message list was drawn below status bar. Maybe something I can fix with styling or tweaking AndroidManifest?

![image](https://user-images.githubusercontent.com/1794792/111498558-b8a3bc00-874a-11eb-9bb8-b388d6deddb8.png)

**Comment by Ayyanchira** [comment]
> Yeah, that was it, thanks! Would be a better user experience if the empty state had something in it, maybe some "No messages" text?

@korva, you can [refer to this doc here](https://support.iterable.com/hc/en-us/articles/360039091471#empty-state) to add title and message to empty inbox screen.
Thank you :)
