### ISSUE TITLE
Update to firebase messaging 22.0.0

### ISSUE THREAD

**Issue by JeremiahStephenson** [Iterable/iterable-android-sdk#346]
It looks like you're using some methods that were deprecated in later versions of firebase messaging and now they're removed in the latest release. If a developer needs to include firebase messaging separate from iterable then it will result in a crash if they specify version 22.0.0+. Thanks.

**Comment by davidtruong** [comment]
Thanks Jeremiah,
Opened up a ticket to investigate the deprecated firebase methods. Which FCM methods were you specifically referencing for 22.0.0?

**Comment by JeremiahStephenson** [comment]
Specifically it's anything with `FirebaseInstanceId`. That's been replaced with `FirebaseMessaging`.
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId

**Comment by DroidPulkit** [comment]
Good find @JeremiahStephenson, our company is also facing issue if we upgrade firebase to latest version, then our test cases fail, as FirebaseInstanceId is being used over here https://github.com/Iterable/iterable-android-sdk/blob/master/iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java#L89

**Comment by davidtruong** [comment]
@JeremiahStephenson 
We will take a look at a fix for this in future releases. In the mean time: per the release notes from Google, have you tried adding the dependency for firebase-iid? Let me know if that works for you.
 
`Cloud Messaging version 22.0.0
Removed dependency on the deprecated Firebase Instance ID SDK.

Caution: This is a breaking change for apps that use FCM and the deprecated Firebase Instance ID API to manage registration tokens.
We strongly recommend migrating to FCM's token APIs. If you're unable to migrate to the replacement APIs, add a direct dependency on the firebase-iid library to your build.gradle file.`

**Comment by searchy2** [comment]
This is also an issue for me as well.

**Comment by Ayyanchira** [comment]
Thank you for bringing this one up.
[Version 3.3.1](https://github.com/Iterable/iterable-android-sdk/releases/tag/3.3.1) is released and should fix the above mentioned crash issues. Here is the link to [support doc](https://support.iterable.com/hc/en-us/articles/360035019712#v3-3-1).
 Closing the ticket. 
Please let us know if the problem persists.
