### ISSUE TITLE
Android 12 support (missing exported element)

### ISSUE THREAD

**Issue by korva** [Iterable/iterable-android-sdk#370]
Building for Android 12 / API 31 seems to fail because the new required `exported` element is not present in iterableapi-ui AndroidManifest.xml. Error message is "Manifest merger failed with multiple errors"

File in question: https://github.com/Iterable/iterable-android-sdk/blob/master/iterableapi-ui/src/main/AndroidManifest.xml

See https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by korva** [comment]
Still an issue with v3.3.5. This prevents API level 31 usage without hacks.

**Comment by Ayyanchira** [comment]
Hi @korva thanks for bringing this to notice. [3.3.6](https://github.com/Iterable/iterable-android-sdk/releases/tag/3.3.6) has it fixed.
Let us know if the issue persists.
