### ISSUE TITLE
Notification Click Issue

### ISSUE THREAD

**Issue by QumberAbbas12** [Iterable/iterable-android-sdk#375]
When the users click on the notifications, activity is recreated even when the app is in the foreground.

I want the following behavior
1) When the app is killed open it
2) When app is in the background, bring it to the front.
3) When the app is in the foreground, do nothing.

**Comment by Ayyanchira** [comment]
Hi @QumberAbbas12 , were you able to achieve desired results?

What value are you returning in callbacks - `handleIterableURL`? or are you implementing `handleIterableCustomAction`?

**Comment by vbabenkoru** [comment]
@QumberAbbas12 This should already be possible with some configuration but unfortunately we cannot assist with app-specific questions in Github issues. Please contact Customer Support and we'll help you configure the SDK to achieve this.
