### ISSUE TITLE
IterableInAppFragmentHTMLNotification IllegalStateException

### ISSUE THREAD

**Issue by imondok** [Iterable/iterable-android-sdk#379]
Hi!
We have multiple crash logs reported by firebase crash analytics on android. Iterable SDK v.3.2.9

`Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceStateat androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:250)at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification.access$601(IterableInAppFragmentHTMLNotification.java:37)at com.iterable.iterableapi.IterableInAppFragmentHTMLNotification$5.run(IterableInAppFragmentHTMLNotification.java:386)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)at android.view.Choreographer.doCallbacks(Choreographer.java:809)at android.view.Choreographer.doFrame(Choreographer.java:740)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loop(Looper.java:246)at android.app.ActivityThread.main(ActivityThread.java:8512)at java.lang.reflect.Method.invoke(Method.java)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by Ayyanchira** [comment]
Hi @imondok , we added a fix for it in version [3.2.11](https://github.com/Iterable/iterable-android-sdk/releases/tag/3.2.11).
Can you please try this version and let us know if the issue resolves?

**Comment by ken-brown** [comment]
Closing issue
