### ISSUE TITLE
Notification crash on Android 12

### ISSUE THREAD

**Issue by JeremiahStephenson** [Iterable/iterable-android-sdk#385]
`IterablePushActionReceiver` contains this line of code `context.sendBroadcast(new Intent(Intent.ACTION_CLOSE_SYSTEM_DIALOGS))` which now causes a `SecurityException` when the user taps on the notification and thus crashes the app. 
https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs

**Comment by JeremiahStephenson** [comment]
@Ayyanchira Any chance you could take a look at this?

**Comment by Mturner005** [comment]
@JeremiahStephenson Thank you for bringing this to our attention.  I've opened up a ticket with the team here to look into this issue.  We will let you know as soon as we have an update / more information.

- Michael Turner
