### ISSUE TITLE
UserId persisted and token not requested...?

### ISSUE THREAD

**Issue by KirkBushman** [Iterable/iterable-android-sdk#386]
Hi,

We are seeing a weird behaviour with this SDK, we implemented it in our app a few months ago with no issues, all of a sudden we realized events are not been sent anymore last week.

The issue we're seeing is that the UserId is getting cached in the SDK through a SharedPrefs instance and is getting loaded at the init of the SDK.

Once we call `public void setUserId(@Nullable String userId)` we see that there is no request for a new token since it returns in the first line at: 
```java
if (_userId != null && _userId.equals(userId)) {
    return;
}
```

We find the _userId variable is already set.

So all of our events call are erroring out since the token is never being set...
We are getting around the issue by resetting the UserId to null at the beginning every time, which is not ideal since we are not reusing valid tokens if present on reenter...

Is this behavior intended? Were there changes in the SDK to implement this behavior? If the token is null and the UserId already set should we call for a new token somewhere? Are we doing something wrong in our implementation? 

Thanks in advance

**Comment by vbabenkoru** [comment]
@KirkBushman Thank you for reporting this.
Did you have a previous version of the app without JWT and then released a version with JWT implemented? Trying to figure out how `SharedPreferences` could have the userId but not the token.

**Comment by KirkBushman** [comment]
@vbabenkoru 

I don't think that's the issue: since we added Iterable to our app it only changed slightly in months, the JWT was there since the beginning.
From how our backend works, we need a bit of time since the user is created and when a JWT token can be generated (completing onboarding, getting the new permissions, ...): We observe that whenever we set the UserId but the token is not set in the callback for whatever reason, the SDK will never try again to fetch it.
It will attempt to report events getting JWT errors, and if you try to set the same UserId again, it won't try to get a valid token (the variable will stay at null).

Right now we're fixing this by trying to initialize the SDK at the point that we can actually generate a token, and if we need to reset the userId, we just set the UserId to null first, so we are granted that it will be different from the one saved.

I would suggest 2 things to improve the situation:
- If for any reason we're not set up to report events, let's not make the call (possibly giving more info on what's wrong). 
- If we're trying to set a userId or email (the same as the one stored) but the token is null, let's try again to generate another token.

**Comment by Mturner005** [comment]
@KirkBushman Curious if you've seen (or not seen, here) the SDK retrieve a new JWT upon a failed request?

**Comment by KirkBushman** [comment]
If the failed request sets the token to null, or if it's not set at all, I would expect it to try again. If the userId is set but the JWT is not, it won't do it. Or at least this is what I'm seeing here.

**Comment by Mturner005** [comment]
@KirkBushman Our team is still investigating this issue, but just wanted to confirm which version of our SDK you are experiencing this behavior with / you're currently using?

**Comment by Mturner005** [comment]
@KirkBushman It's been a while since we've heard from you.  We're going to close this ticket out, but if you still required further assistance with this issue we recommend you email support@iterable.com.  Thanks!
