### ISSUE TITLE
Android 12 Notification Trampoline Restrictions

### ISSUE THREAD

**Issue by JeremiahStephenson** [Iterable/iterable-android-sdk#401]
Handling a notification tap with a pending intent that goes to a broadcast receiver is no longer allowed in Android 12. This results in nothing happening when the user taps on the notification.
https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines

**Comment by vbabenkoru** [comment]
@JeremiahStephenson We're aware of the issue and are working on it. Please open a Support ticket to make sure you get notified when we release a fix for it. Thank you!

**Comment by themanol** [comment]
This is a blocker issue for us, do you have an ETA for a release with this fix?
Thanks

**Comment by Ayyanchira** [comment]
https://github.com/Iterable/iterable-android-sdk/releases/tag/3.4.1 is released with Trampoline Restriction fix
