### ISSUE TITLE
Crashes in IterableNetworkConnectivityManager. startNetworkCallback

### ISSUE THREAD

**Issue by korva** [Iterable/iterable-android-sdk#417]
I have started to receive some crashes for a small ( <1%) percentage of users from our production app with Iterable.
These happen on multiple different devices, all running Android 11.

Crash log and stack trace:

Fatal Exception: java.lang.RuntimeException
Unable to create application <our app application id>: java.lang.SecurityException: Package android does not belong to 10290

com.iterable.iterableapi.IterableNetworkConnectivityManager.startNetworkCallback (IterableNetworkConnectivityManager.java:50)
com.iterable.iterableapi.IterableNetworkConnectivityManager.<init> (IterableNetworkConnectivityManager.java:40)
com.iterable.iterableapi.IterableNetworkConnectivityManager.sharedInstance (IterableNetworkConnectivityManager.java:30)
com.iterable.iterableapi.OfflineRequestProcessor.<init> (OfflineRequestProcessor.java:36)
com.iterable.iterableapi.IterableApiClient.setOfflineProcessingEnabled (IterableApiClient.java:53)
com.iterable.iterableapi.IterableApi.loadLastSavedConfiguration (IterableApi.java:317)
com.iterable.iterableapi.IterableApi.initialize (IterableApi.java:306)

Looks like this has started when updating to Iterable 3.3.5 a few months ago.
Updating to latest library (3.4.0) does not seem to fix it. Any ideas?

**Comment by vbabenkoru** [comment]
Seems to be this Android bug: https://issuetracker.google.com/issues/175055271

**Comment by korva** [comment]
Hi, this is still the number 1 crash in our app, any news on when it could be fixed?
