### ISSUE TITLE
Devices not linked to users while initialization

### ISSUE THREAD

**Issue by mglal** [Iterable/iterable-android-sdk#424]
I had a working app for more than 3 years, last week I updated the SDKs to the following:
- Iterable SDK -> 3.4.0
- Firebase-messaging SDK -> 20.3.0 now on v4.1.6 we use this.
While I am on Debug version everything is working fine. Once I build a release version and release it to Play store, I can see the new user is added to Iterable and the device object is always empty.

What could be the problem here?

**Comment by Ayyanchira** [comment]
Thank you for reaching out. I would suggest opening a support ticket and we should be able to look more into it @mglal.

**Comment by Ayyanchira** [comment]
Also do a quick check if you are using API key of a different project. It may happen that API key being used is the one from intended for Debug/Sandbox project.

**Comment by Ayyanchira** [comment]
@mglal , have the issue resolved?
