### ISSUE TITLE
Subscribe the user to a message type or channel

### ISSUE THREAD

**Issue by kdybicz** [Iterable/iterable-android-sdk#453]
Hi! We might be missing something, so hope you could help us sort that out. We're wondering how using the SDK we could manage user subscriptions? Such functionality must be available from the SDK level, right?

**Comment by Ayyanchira** [comment]
Hi @kdybicz , Iterable has https://api.iterable.com/api/docs#users_updateSubscriptions api for managing user subscription. 
The SDK also has a public method - [updateSubscriptions](https://github.com/Iterable/iterable-android-sdk/blob/e6c4349377a9bc31054035be5ee860fad9c6cc66/iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java#L944) which can be handy as well.

Hope this helps.

**Comment by kdybicz** [comment]
@Ayyanchira mentioned method from the SDK is only half of the equation. When user reinstall the app or install it on new device we want to be sure that we can show him current subscriptions setup, but... as far as I can see there is no way of fetching that information back your servers using SDK, is it?
