### ISSUE TITLE
Master branch fails at runtime

### ISSUE THREAD

**Issue by steelbrain** [Iterable/iterable-android-sdk#46]
We're running Iterable's https://github.com/Iterable/iterable-android-sdk/commit/5624918e09adb11e971c2047f438d921139b2aa9, it compiles successfully but crashes the app on open, here's the stacktrace we're getting

```
07-19 03:37:48.875 E/AndroidRuntime( 7062): FATAL EXCEPTION: AsyncTask #2
07-19 03:37:48.875 E/AndroidRuntime( 7062): Process: com.truebill, PID: 7062
07-19 03:37:48.875 E/AndroidRuntime( 7062): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv;
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:34)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at com.google.android.gms.iid.zzo.<init>(Unknown Source:2)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:22)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source:1)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at io.intercom.android.sdk.gcm.IntercomGcmImplementation.registerToken(IntercomGcmImplementation.java:26)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at io.intercom.android.sdk.IntercomPushManager.registerGcmToken(IntercomPushManager.java:65)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at io.intercom.android.sdk.RealIntercom$1.run(RealIntercom.java:124)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at java.lang.Thread.run(Thread.java:764)
07-19 03:37:48.875 E/AndroidRuntime( 7062): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzv" on path: DexPathList[[zip file "/data/app/com.truebill-VqzA1Up-dbmkR-G33NBugw==/base.apk"],nativeLibraryDirectories=[/data/app/com.truebill-VqzA1Up-dbmkR-G33NBugw==/lib/x86, /data/app/com.truebill-VqzA1Up-dbmkR-G33NBugw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-19 03:37:48.875 E/AndroidRuntime( 7062): 	... 11 more
```

The error seems to originate from Intercom, but it goes away when we remove Iterable as a dependency. Any ideas on how to debug this?

**Comment by vbabenkoru** [comment]
Hi @steelbrain, thanks for reporting! The current version still depends on GCM, so you need to make sure `com.google.android.gms:play-services-gcm` is imported as a dependency. We're currently wrapping up FCM migration in [this branch](/Iterable/iterable-android-sdk/tree/chore/ITBL-4897-support-FCM). The next version (3.0.0) will ship with FCM support.

**Comment by steelbrain** [comment]
@vbabenkoru We're already importing GCM (we have this `build.gradle`). Any ideas what else could we try?

```
compile 'com.google.android.gms:play-services-gcm:11.8.0'
```

**Comment by vbabenkoru** [comment]
@steelbrain it looks like there is a version mismatch between FCM and GCM dependencies. IIRC they're using the same infrastructure. Iterable SDK pulls this version: `implementation 'com.google.android.gms:play-services-gcm:15.0.1'`. Looks like importing an older version might cause it the GCM/FCM dependencies to break internally. Try running `./gradlew app:dependencies` and look for `play-services-gcm` in the dependency tree - do multiple libraries reference it and which versions do they reference?

**Comment by vbabenkoru** [comment]
Hi @steelbrain, were you able to resolve it? Do you still need help with this?

**Comment by steelbrain** [comment]
Hi @vbabenkoru 

Haven't been able to resolve it yet sadly :(
I've uploaded the module map [in a gist](https://gist.github.com/steelbrain/6248eead0b5d714c4dad710ed5917309). There's a disparity between versions (11.0.8 vs 15.0.1),

Tried forcing the resolution to both one by one with
```
resolutionStrategy {
  force 'com.google.android.gms:play-services-gcm:15.0.1'
}
```
but neither worked. Not much experienced with the Android ecosystem so apologies for rookie mistakes

**Comment by vbabenkoru** [comment]
This dependency tree doesn't have Iterable in it.. Can you generate another one with Iterable SDK included?

**Comment by steelbrain** [comment]
I've updated the original gist with outputs from default and the forced resolutions

**Comment by vbabenkoru** [comment]
Have you tried specifying this?
`compile 'com.google.android.gms:play-services-gcm:15.0.1'`
It looks like `play-services-gcm` is set to 11.0.8, but other implicit dependencies are still 15.0.1, that may lead to crashes due to inconsistent versions. One way is to update everything to 15.0.1, another is to override versions for other packages.

**Comment by vbabenkoru** [comment]
Also, I just googled the error, and it appears to be related `react-native-device-info`, a package you're using:
https://github.com/rebeccahughes/react-native-device-info/issues/445
https://github.com/rebeccahughes/react-native-device-info/issues/448

**Comment by vbabenkoru** [comment]
Hey @steelbrain did any of this help?

**Comment by steelbrain** [comment]
Thank you for all your help @vbabenkoru 

The error ended up being one of our Android config files (not directly related to either RN device info or Iterable). Thank you for your time
