### ISSUE TITLE
Malware detected when Push Notification Open Tracking enabled

### ISSUE THREAD

**Issue by guillaume-gouchon** [Iterable/iterable-android-sdk#48]
Hi,

when enabling open tracking :

        <receiver
            android:name="com.iterable.iterableapi.IterablePushOpenReceiver"
            tools:ignore="ExportedReceiver">
            <intent-filter>
                <action android:name="com.iterable.push.NOTIF_OPENED" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

if you have any antivirus installed on your device (Bitdefender app for example), it will categorise your app as a malware.

Could you please have a look and find a way to avoid this ?

Thanks.

Best regards

**Comment by davidtruong** [comment]
@guillaume-gouchon: Thanks for reporting this, we'll take a look at this and see why it is the case.

If you have any leads on what about the receiver is causing it to be flagged, please let us know.

**Comment by vbabenkoru** [comment]
@guillaume-gouchon try setting `android:exported="false"` on the receiver.

**Comment by guillaume-gouchon** [comment]
I tested it and it works. Thanks !
