### ISSUE TITLE
Official Flutter SDK

### ISSUE THREAD

**Issue by chillbrodev** [Iterable/iterable-android-sdk#482]
Hello Iterable Devs,

I know this may not be the best place to ask this question but I could not find another location. 

I am working on a Flutter project and was writing to see if there were plans for Iterable to release an official Flutter SDK. There is an unofficial wrapper which works okay but would be great to see Iterable support Flutter directly.

**Comment by Ayyanchira** [comment]
Thanks for writing in @chillbrodev ! We appreciate the idea :) however, currently there are no plans for having FlutterSDK. May be sometime in future! :)
Also, if you have any ideas, would love to see them in [ideas section](https://github.com/Iterable/iterable-android-sdk/discussions/categories/ideas)
