### ISSUE TITLE
Outdated / Incomplete Documentation

### ISSUE THREAD

**Issue by scottkruse** [Iterable/iterable-android-sdk#55]
(https://support.iterable.com/hc/en-us/articles/115000331943-Setting-up-Android-Push-Notifications)

This post recommends adding permissions that are mentioned to be obsolete and harmful if migrating to FCM based on this information https://developers.google.com/cloud-messaging/android/android-migrate-fcm

This post also recommends to use a deprecated method `(registerForPush(_, _, {messaging_provider}`) to register for push notifications in the section labeled GCM -> Firebase migration. 

Also the post suggests to include Receivers in the manifest that no longer exist in the SDK as of the most recent 3.x releases https://github.com/Iterable/iterable-android-sdk/releases/tag/3.0.0

As a result i'm currently unable to send push notifications via Iterable's dashboard https://app.iterable.com/integrations/mobilePush despite correct FCM tokens being correctly registered and being able to successfully send push notifications via FCM dashboard https://console.firebase.google.com/

**Comment by vbabenkoru** [comment]
Thank you for bringing our attention to this! We've updated the documentation on our Support site and added links to the guides on Github. Using only the documentation provided in the Readme here should be enough to install the SDK.

**Comment by scottkruse** [comment]
Thank you for the prompt response!
