### ISSUE TITLE
InApp Campaigns Impimentation.

### ISSUE THREAD

**Issue by ashishsharma30** [Iterable/iterable-android-sdk#58]
Hello Guys,

I have tried to implement InApp Campaigns based on provide github instructions, And try to handle InApp message "spawnInAppNotification" but never receive any messages. Please suggest me where and how to use this method "spawnInAppNotification".
Also please provide me sample code for better implementation.

Thanks,
Ashish

**Comment by davidtruong** [comment]
Can you verify if you have in-app notifications queued up for you user?
You can check the /api/inApp/getMessages api to see what messages are queued up?

**Comment by ashishsharma30** [comment]
I verified everything, I have issue in android code. In iOS it's working fine.
Your android SDK on github repository not updated and there is no sample code how to implement.
Can you Please suggest me where and how to use this method "spawnInAppNotification" in android or provide me sample code for better implementation.
Thanks.

**Comment by ashishsharma30** [comment]
I used compile 'com.iterable:iterableapi:3.0.0' version in my code. And follow step which is on github.
Ok, I'll try again.
Thanks

**Comment by ashishsharma30** [comment]
This class IterableApiHelper not available in your SDK. I tried your code in Java ( In MainActivity).
 
IterableApi.getInstance().spawnInAppNotification(getApplicationContext(), new IterableHelper.IterableActionHandler() {
                    @Override
                    public void execute(String data) {
                        Log.e("HandleInApp", "Redirected to: " + data);
                    }
                });

But, still not working. Can you Please suggest me how to use this method "spawnInAppNotification" in android (Java) or provide me sample code for better implementation (In Java).

**Comment by ashishsharma30** [comment]
Thanks, It's working fine. :+1: 

Java Example : 
IterableApi.getInstance().spawnInAppNotification(getActivity(), new IterableHelper.IterableActionHandler() {
                      @Override
                                public void execute(String data) {
                                          Log.e("HandleInApp", "Redirected to: " + data);
                               }
                       });
Note : If you are using fragment write this code in fragment.

**Comment by davidtruong** [comment]
Glad you got it working.
