### ISSUE TITLE
NullPointerException in com.iterable.iterableapi.IterableInAppHTMLNotification$2.run

### ISSUE THREAD

**Issue by BrooksZhang** [Iterable/iterable-android-sdk#60]
Crashlytics reported this crash issue since we upgraded to iterable 3.0.1 from 2.2.0
![image](https://user-images.githubusercontent.com/36977139/46108606-8fb5a680-c232-11e8-9eac-fe81a4d22575.png)
The NPE happened here as notification is set to null in onStop method
![crashplace](https://user-images.githubusercontent.com/36977139/46108698-c7245300-c232-11e8-8cf4-0bd1b40e7792.png)

**Comment by davidtruong** [comment]
Thanks for the crash report. We'll make sure to add in the error checking in the resize function when the notification gets set to null.

**Comment by vbabenkoru** [comment]
@BrooksZhang Thanks for the report! This has been fixed and will be released with the next update.

**Comment by BrooksZhang** [comment]
Hi Victor,

Thanks for the fixing. I’m looking forward to having the next release.

Thanks,
Brooks

**Comment by pete-alphero** [comment]
@vbabenkoru Do you have an ETA on the release date for the next update?

**Comment by vbabenkoru** [comment]
@pete-alphero @BrooksZhang 3.0.3 has been released.
