### ISSUE TITLE
Crash Displaying In-App HTML Message

### ISSUE THREAD

**Issue by SRoseDev** [Iterable/iterable-android-sdk#64]
The SDK can cause a crash is another app has focus when trying to show the In-App message. I was able to recreate this using Facebook Messenger while using our app with Iterable. The Crashlytics trace is below:

Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'android.view.Window com.iterable.iterableapi.j.getWindow()' on a null object reference Raw Text
--
  | com.iterable.iterableapi.IterableInAppHTMLNotification$2.run (IterableInAppHTMLNotification.java:185)
  | android.os.Handler.handleCallback (Handler.java:789)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by vbabenkoru** [comment]
@SRoseDev Thanks for the report! Please update to the latest version, this bug was fixed in 3.0.3. Here is the original report: #60. Thank you!
