### ISSUE TITLE
Update Glide to the latest version

### ISSUE THREAD

**Issue by cmargonis** [Iterable/iterable-android-sdk#708]
Hello everyone 👋 

As we are trying to remove the use of `jetifier` from our project to decrease our build time, we noticed that iterable depends on a legacy Glide version `4.8.0` (latest stable is [4.16.0](https://github.com/bumptech/glide/releases/tag/v4.16.0)) . I noticed that it was added in this #508 PR and I'm not sure if there was any issue which prevented the use of newer Glide versions.

We would very much appreciate it if it could be updated (I can also open a PR updating it).

**Comment by evantk91** [comment]
@cmargonis We will take a look at upgrading the Glide version. Thanks for raising this issue.

**Comment by jena-chakour** [comment]
Hi @cmargonis thanks again for raising this issue-- please see our updated Android SDK [version 3.5.1](https://github.com/Iterable/iterable-android-sdk/releases/tag/3.5.1), which includes an update to the Glide library

**Comment by cmargonis** [comment]
Thank you very much @jena-chakour !
