### ISSUE TITLE
⚠️ IterableAuthManager.isTimerScheduled field is not reset after email has changed 

### ISSUE THREAD

**Issue by rkushch-asp** [Iterable/iterable-android-sdk#757]
`void scheduleAuthTokenRefresh(long timeDuration, final boolean isScheduledRefresh, final IterableHelper.SuccessHandler successCallback) ` method checks if there is any scheduled task using `isTimerScheduled` field. When the user successfully registers the device token - SDK schedules `queueExpirationRefresh.` If the user changes the email before the expiration - the `IterableAuthManager::isTimerScheduled` field will remain equal to true.  Under this condition, If the user changes the email and the app provides the invalid JWT token due to any reason(API failed, no active session, etc.) - SDK is not able to schedule a retry because `isTimerScheduled = true.`

Steps to reproduce:
1. Call  `IterableApi.getInstance().email = someEmail1`
2. Call `IterableApi.getInstance().registerForPush()`
3. Return a valid token that expires in more than 3 minutes in the `IterableAuthHandler::onAuthTokenRequested.`
4. Call `IterableApi.getInstance().disablePush()`
5. Call  `IterableApi.getInstance().email = someEmail2`
6. Call `IterableApi.getInstance().registerForPush()`
7. Throw an exception in the `IterableAuthHandler::onAuthTokenRequested.`

:white_check_mark: Expected result: `IterableAuthHandler::onAuthTokenRequested` is called in some time according to the `RetryPolicy.`
:warning: Actual result: `IterableAuthHandler::onAuthTokenRequested` is not called because `IterableAuthManager::isTimerScheduled == true` after `queueExpirationRefresh`  was called for a previously registered email(someEmail1)

**Comment by Ayyanchira** [comment]
Thank you for trying out the new version of SDK and reporting the issue @rkushch-asp .
